- hosts: wiredcraft-docker-registry
  become: true
  tasks:
    - name: install dependencies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: GPG_keys
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: enable docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: priviledge the non root user
      shell:
          "sudo usermod -aG docker ${USER}"
    - name: docker compose
      shell:
          'sudo curl -L "https://github.com/docker/compose/releases/download/1.28.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
    - name: docker compose folder
      shell:
          "sudo chmod +x /usr/local/bin/docker-compose"
  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted
