name: Docker Series Builds

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker build python
      run: |
        docker build . -t hello-api/python:1.0.0
    
