name: Docker Series Builds

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: insecure registry
      run: |
          DOCKER_OPTS='--insecure-registry 35.193.64.108:5000'
    - name: docker restart
      run: |
          sudo service docker restart
    - name: docker build python
      run: |
        docker build . -t hello-api/wiredcraft:1.0.0
    - name: docker tag
      run: |
        docker tag hello-api/wiredcraft:1.0.0 35.193.64.108:5000/hello_api:v2.0
    - name: docker push image
      run: |
        docker push 35.193.64.108:5000/hello_api:v2.0
#        echo "need to push to insecure"
         
         
