name: Docker Series Builds

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: docker build python
      run: |
        docker build . -t hello-api/wiredcraft:1.0.2
    - name: docker tag
      run: |
        docker tag hello-api/wiredcraft:1.0.2 server.jahanxb.xyz/hello_api:v5.1
    - name: docker push image
      run: |
        docker push server.jahanxb.xyz/hello_api:v5.1
#        echo "need to push to inseas cuse  "
         
         
