name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
    - uses: actions/checkout@v2
    - run: docker build . --tag hello-api/wiredcraft:1.0.0
    - name: docker push
      run: |
       echo "here we push it"
    
