name: Docker Series Builds

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: docker build python
      run: |
        docker build . -t hello-api_v1/wiredcraft:1.0.3
    - name: docker tag
      run: |
        docker tag hello-api_v1/wiredcraft:1.0.3 server.jahanxb.xyz/hello_api_v1:v5.2
    - name: docker push image
      run: |
        docker push server.jahanxb.xyz/hello_api_v1:v5.2
#        echo "need to push to inseas cuske  "
         
         
