name: Docker Series Builds

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: insecure registry
      run: |
          ls
    - name: docker build python
      run: |
        docker build . -t hello-api/wiredcraft:1.0.0
    - name: docker tag
      run: |
        docker tag hello-api/wiredcraft:1.0.0 35.193.64.108:5000/hello_api:v2.0
    - name: docker push image
      run: |
        echo "need to push to insecure"
#        docker push 35.193.64.108:5000/hello_api:v2.0
         
