name: Docker Series Builds

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: docker build python
      run: |
        docker build . -t hello-api/wiredcraft:1.0.3
    - name: docker tag
      run: |
        docker tag hello-api/wiredcraft:1.0.3 server.jahanxb.xyz/hello_api:v5.4
    - name: docker push image
      run: |
        docker push server.jahanxb.xyz/hello_api_v1:v5.4
#        echo " You can add server url in secrets if needed  "
         
         
